import { tool } from "ai"
import { z } from "zod"

import { getArtifactById } from "@/lib/db/queries/artifacts"
import type { ToolRegistration } from "./registry"

const ID_PATTERN = /^[a-zA-Z0-9_-]{1,21}$/

const DEFAULT_MAX_CHARS = 50_000
const HARD_CAP_CHARS = 200_000

/**
 * Factory: creates the read_artifact tool bound to a specific chatId.
 * Lets the LLM read the content of an artifact that was generated by an
 * external tool (youtube_analyze, extract_branding, deep_research, …) or
 * created earlier in the conversation and is no longer in context.
 *
 * Conversation-scoped: only artifacts of this chatId can be read.
 */
export function readArtifactTool(chatId: string) {
  return tool({
    description:
      "Read the full content of an artifact that exists in this conversation. " +
      "Use this when the user wants you to react to, comment on, or further process an artifact " +
      "whose content you don't already know — typically artifacts created by external tools like " +
      "youtube_analyze, extract_branding, deep_research, create_quiz, create_review, " +
      "or older artifacts whose content has fallen out of the conversation context. " +
      "Do NOT call this for artifacts you just created with create_artifact (you already know the content). " +
      "Do NOT call this for image or audio artifacts (no readable text content).",
    inputSchema: z.object({
      artifactId: z
        .string()
        .describe("The artifact ID to read, as returned by the tool that created it."),
      reason: z
        .string()
        .max(300)
        .describe("Brief explanation why you need the content (e.g. 'user wants comparison', 'user asked for a summary')."),
      maxChars: z
        .number()
        .int()
        .positive()
        .max(HARD_CAP_CHARS)
        .optional()
        .describe(
          `Max characters to return. Default ${DEFAULT_MAX_CHARS}. Use a smaller value when reading multiple artifacts at once.`
        ),
    }),
    execute: async ({ artifactId, maxChars }) => {
      if (!ID_PATTERN.test(artifactId)) {
        return { error: "Invalid artifact ID." }
      }

      const artifact = await getArtifactById(artifactId)
      if (!artifact) {
        return { error: "Artifact not found." }
      }

      // Conversation scope: hard boundary against cross-chat leaks.
      if (artifact.chatId !== chatId) {
        return { error: "Artifact does not belong to this conversation." }
      }

      if (artifact.type === "image" || artifact.type === "audio") {
        return {
          error: `${artifact.type} artifacts have no readable text content. Tell the user what you can see in the chat or ask what they want to do with it.`,
        }
      }

      const limit = Math.min(maxChars ?? DEFAULT_MAX_CHARS, HARD_CAP_CHARS)
      const fullContent = artifact.content ?? ""
      const truncated = fullContent.length > limit
      const content = truncated ? fullContent.slice(0, limit) : fullContent

      return {
        artifactId: artifact.id,
        title: artifact.title,
        type: artifact.type,
        language: artifact.language ?? undefined,
        version: artifact.version,
        content,
        charCount: fullContent.length,
        truncated,
        createdAt: artifact.createdAt.toISOString(),
        ...(truncated && {
          truncationHint: `Content was truncated at ${limit} chars (full length: ${fullContent.length}). Call read_artifact again with a higher maxChars if you need more.`,
        }),
      }
    },
  })
}

export const registration: ToolRegistration = {
  name: "read_artifact",
  label: "Artifact lesen",
  icon: "BookOpen",
  category: "core",
  customRenderer: false,
}
